version: '3'
services:
  backend:
    build:
      context: ./backend
    image: backend-speakit:latest
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: frontend-speakit:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
