version: '3'
services:
  backend:
    build: ./backend
    image: backend-speakit:latest
    ports:
      - "5000:5000"
    environment:

  frontend:
    build: ./frontend
    image: frontend-speakit:latest
    ports:
      - "80:80"
    depends_on:
      - backend
