version: '3'
services:
  backend:
    build:
      context: ./backend
      args:
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}
        - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
    image: backend-speakit:latest
    ports:
      - "5000:5000"
  frontend:
    build: ./frontend
    image: frontend-speakit:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
